// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0_dcwSAC-A3NzPJFRQZZOevkO4dYGfdY',
    appId: '1:248931132785:web:370479f8c4efd4b35e82d0',
    messagingSenderId: '248931132785',
    projectId: 'bewtie-51fc2',
    authDomain: 'bewtie-51fc2.firebaseapp.com',
    storageBucket: 'bewtie-51fc2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjY2FhuQ9P8QYBNoRBYIha0dLLRJnohDg',
    appId: '1:248931132785:android:4b4bc48dfcfa47245e82d0',
    messagingSenderId: '248931132785',
    projectId: 'bewtie-51fc2',
    storageBucket: 'bewtie-51fc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc1BPGF4tkhWQ4q4KyX8zAjixdHUqehLI',
    appId: '1:248931132785:ios:9139847a5b5fd6c45e82d0',
    messagingSenderId: '248931132785',
    projectId: 'bewtie-51fc2',
    storageBucket: 'bewtie-51fc2.appspot.com',
    iosBundleId: 'com.bewtie.app',
  );
}
